/**
 * Regenerates the translation backlog snapshot that `src/i18n/parity.test.ts`
 * enforces. Run it after translating keys (the snapshot may only shrink) or
 * after adding English keys you cannot translate in the same change.
 *
 *   bun run script/i18n-baseline.ts
 */
import { writeFileSync } from "fs"
import { fileURLToPath } from "url"
import { LOCALES } from "../src/i18n/locales"
import { dict as en } from "../src/i18n/en"

const enKeys = Object.keys(en)
const untranslated = new Set<string>()
const counts: Record<string, number> = {}

for (const locale of LOCALES) {
  const { dict } = await import(`../src/i18n/${locale}`)
  const present = new Set(Object.keys(dict))
  const missing = enKeys.filter((key) => !present.has(key))
  missing.forEach((key) => untranslated.add(key))
  counts[locale] = missing.length
}

const out = fileURLToPath(new URL("../src/i18n/untranslated.ts", import.meta.url))
writeFileSync(
  out,
  [
    "// Generated by script/i18n-baseline.ts — do not edit by hand.",
    "// English keys some locale has not translated yet, and how many each locale",
    "// is still missing. parity.test.ts holds both to these numbers.",
    "",
    `export const UNTRANSLATED_KEYS: string[] = ${JSON.stringify([...untranslated].sort(), null, 2)}`,
    "",
    `export const UNTRANSLATED_COUNTS: Record<string, number> = ${JSON.stringify(counts, null, 2)}`,
    "",
  ].join("\n"),
)
console.log(`${untranslated.size} untranslated keys across ${LOCALES.length} locales -> ${out}`)
